In [1]:
import pandas as pd

In [2]:
education = pd.read_csv("./data/education-income.csv")
education

,Neighborhood,Sector #,Population (2010),"Total Pop, 25 and older (2010)",Edu. Attainment: Less than High School (2010),Edu. Attainment: High School Graduate (2010),Edu. Attainment: Assoc./Prof. Degree (2010),Edu. Attainment: Bachelor's Degree (2010),Edu. Attainment: Postgraduate Degree (2010),1999 Median Income ('99 Dollars),2009 Median Income ('09 Dollars),1999 Median Income ('11 Dollars),2009 Med. Income ('13 Dollars),Est. Pop. for which Poverty Calc. (2010),Est. Pop. Under Poverty (2010),Est. Percent Under Poverty (2010)
0,Allegheny Center,3,933,609,18.7%,44.5%,17.2%,15.8%,3.8%,"$16,964","$20,911","$22,535","$22,793",954,324,34.0%
1,Allegheny West,3,462,239,9.2%,28.9%,6.7%,44.8%,10.5%,"$26,638","$41,761","$35,386","$45,519",239,12,5.0%
2,Allentown,6,"2,500","1,729",23.0%,63.3%,6.6%,5.6%,1.5%,"$22,539","$29,274","$29,941","$31,909","2,212",630,28.5%
3,Arlington,7,"1,869","1,232",14.9%,65.3%,10.1%,7.1%,2.5%,"$27,167","$25,119","$36,089","$27,380","1,779",361,20.3%
4,Arlington Heights,7,244,166,18.1%,74.1%,0.0%,7.8%,0.0%,"$18,646","$9,417","$24,769","$10,265",293,169,57.7%
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85,Upper Lawrenceville,13,"2,669","1,875",16.2%,65.7%,7.0%,9.4%,1.7%,"$24,883","$31,779","$33,055","$34,639","2,814",722,25.7%
86,West End,4,254,86,12.8%,36.0%,24.4%,26.7%,0.0%,"$21,382","$41,250","$28,404","$44,963",116,0,0.0%
87,West Oakland,14,"2,604","1,036",12.0%,46.7%,4.1%,20.1%,17.2%,"$23,517","$20,962","$31,240","$22,849","1,626",758,46.6%
88,Westwood,4,"3,066","2,408",10.7%,51.4%,10.0%,13.2%,14.7%,"$36,820","$49,877","$48,912","$54,366","3,220",186,5.8%
89,Windgap,4,"1,369",979,10.1%,67.1%,12.7%,6.3%,3.8%,"$31,601","$40,982","$41,979","$44,670","1,333",72,5.4%